### PR TITLE
Pac4j 1.8.4 autocare

### PR DESCRIPTION
**Pull request by kouao**
Simple tweaks to extract user roles & permissions from Jboss Keycloak OpenID Connect server

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for the contribution. Though, there are a few issues with the pull request. It doesn't seem to be properly based on master (the "Merge pull request" button is disabled), the current version of the master is `1.9.0-SNAPSHOT`.

Regarding the implementation, if we want to handle specific data or behaviour for a specific OpenID Connect server, we must stop adding logic to the core `OidcClient`, we must start creating specific clients like it has been done for AzureAD (https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/azuread/AzureAdClient.java) or like I plan for Google (https://github.com/pac4j/pac4j/issues/408) or more generally like we have for all OAuth provider supports.
I have completely rebuilt OAuth support (https://github.com/pac4j/pac4j/pull/448) and will continue with OpenID / OpenID Connect supports, it should be clearer in a week or two.

**Comment by kouao** [comment]
Hello Jerome,
 Thank you for the update.
I will follow your instructions.
Thank you for this great library. 
Regards,
—phil

**Comment by leleuj** [comment]
I updated the OpenID Connect support: we now have a generic client: `OidClient` and specific ones: `AzureAdClient` and `GoogleOidClient`.

I think you should follow what I have done for these clients: they have associated profiles with attributes definitions and manual tests: https://github.com/pac4j/pac4j/tree/master/pac4j-oidc/src/test/java/org/pac4j/oidc/run

**Comment by leleuj** [comment]
Closing for now. Feel free to re-open when you are ready.

**Pull request closed without merging**
