### PR TITLE
Extraction of attributevalues with complex types

### PR DESCRIPTION
**Pull request by fbusselgln**
Hello everyone,

while using Pac4j for SAML Delegate Authentication in CAS, I have encountered a problem when extracting complex type attributes from SAML2 assertions. After checking with the Pac4j codebase, I have noticed that there is no differentiation at all and the value is just being extracted by calling dom.getTextContent(), which stuffs all attribute values from complex types into one long string.

Example:

```
    <saml:AttributeStatement>
      <saml:Attribute Name="Foo">
        <saml:AttributeValue xsi:type="xs:string">Bar</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="Organization"
        NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue>
          <OrganizationType
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:q1="urn:osp:foo:schemas:identity"
            xsi:type="q1:OrganizationType"
            id="ab417e71-3fe8-4981-d629-08d90ef68525">
            <q1:OrganizationName q1:attributeId="urn:osp:foo:attribute:organizationName">Example Corp</q1:OrganizationName>
            <q1:EmailAddress q1:attributeId="urn:osp:foo:attribute:emailAddress">employee@example.com</q1:EmailAddress>
            <q1:Address q1:attributeId="urn:osp:foo:attribute:address">
              <q1:Street q1:attributeId="urn:osp:foo:attribute:street">Example St</q1:Street>
              <q1:StreetNumber q1:attributeId="urn:osp:foo:attribute:streetNumber">123</q1:StreetNumber>
              <q1:City q1:attributeId="urn:osp:foo:attribute:city">ExampleCity</q1:City>
              <q1:ZipCode q1:attributeId="urn:osp:foo:attribute:zipCode">123456</q1:ZipCode>
              <q1:Country q1:attributeId="urn:osp:foo:attribute:country">ExampleCountry</q1:Country>
            </q1:Address>
          </OrganizationType>
        </saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>
```

While the attribute Foo is extracted without a problem, the attribute Organization with it's complex value type is extracted as one large text with line delimiters. After extraction with the current code base, printing the results looks like this:

```
Foo=Bar
Organization=
          
            Example Corp
            employee@example.com
            
              Example St
              123
              ExampleCity
              123456
              ExampleCountry
```

I have implemented a more forgiving extractor. With it the output looks a little better:

```
Foo=Bar
OrganizationName=Example Corp
EmailAddress=employee@example.com
Street=Example St
StreetNumber=123
City=ExampleCity
ZipCode=123456
Country=ExampleCountry
```

What do you think?

Cheers

### CODE REVIEW

**Comment by mmoayyed** [comment]
Have not done a review, but this certainly looks to be worthwhile. Thank you.

Make sure you choose the target branch as master.

**Comment by fbusselgln** [comment]
Ok, now master is the target. Sorry, took a while. ;)

**Comment by leleuj** [comment]
LGTM. Please fix the Checkstyle issues by removing tabs in favor of spaces.

**Comment by fbusselgln** [comment]
Sorry for the tabs, faulty configuration of a new eclipse workspace.

**Comment by fbusselgln** [comment]
The PMD Maven plugin seems to be unhappy, but I have no idea why. Any ideas?

**Comment by leleuj** [comment]
Here is the problem:

```
[INFO] PMD version: 6.21.0
[INFO] PMD Failure: org.pac4j.saml.credentials.SAML2CredentialsTest$SAML2AuthnResponseValidatorForTest:72 Rule:UselessOverridingMethod Priority:3 Overriding method merely calls super.
```

**Comment by fbusselgln** [comment]
Ok, it's not really useless because it changes the visibility (which of course is a subject for a potential discussion..). Adding some noop-content just to satisfy the plugin doesn't seem to be the best way either. Do you have any suggestions?

**Comment by fbusselgln** [comment]
Finally everything is green! \o/

**Comment by fbusselgln** [comment]
Do you have any plans on releasing a new Pac4j version any time soon? :)

**Comment by leleuj** [comment]
Yes, I plan to release v4.5.1 and v5.1.1 next week.

**Comment by fbusselgln** [comment]
Sounds good. Have a nice weekend!

**Comment by leleuj** [comment]
pac4j v5.1.1 has been released.

**Comment by fbusselgln** [comment]
Thank you!

**Comment by jmesny** [comment]
Hi everyone!

This week we upgraded our Pac4j dependency to 5.1.1.
Even if our CI didn't find any problem with this release, it introduced a regression in some client codes.

The problem was detected with an ADFS IdP.
The reason is that this improvement relies on the `xsi:type` attribute of the `AttributeValue` element.

But this attribute is optional and ADFS does not use it.

Here is what the SAML specification says about it ([2.7.3.1.1, line 1239](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)):

> If the data content of an `<AttributeValue>` element is of an XML Schema simple type (such as
`xs:integer` or `xs:string`), the datatype **MAY** be declared explicitly by means of an `xsi:type` declaration
in the `<AttributeValue>` element. If the attribute value contains structured data, the necessary data
elements **MAY** be defined in an extension schema.

I found other people discussing the subject, like [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/b86e246b-08f5-475c-b026-9695c1beda2f/attributestatement-is-not-in-proper-saml20-format) or [here](https://lists.oasis-open.org/archives/saml-dev/201106/msg00000.html).

Here is an excerpt of what the ADFS IdP respond us:
```xml
<AttributeStatement>
    <Attribute xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims" Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" a:OriginalIssuer="https://...">
        <AttributeValue>John</AttributeValue>
    </Attribute>
    <Attribute xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims" Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" a:OriginalIssuer="https://...">
        <AttributeValue>DOE</AttributeValue>
    </Attribute>
    <Attribute xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims" Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" a:OriginalIssuer="https://...">
        <AttributeValue>jdoe@company</AttributeValue>
    </Attribute>
    <Attribute Name="http://schemas.microsoft.com/ws/2008/06/identity/claims/role">
        <AttributeValue>...</AttributeValue>
    </Attribute>
</AttributeStatement>
```

What do you think?

**Comment by leleuj** [comment]
What problem do you have exactly? Any stack trace?

Can you propose a fix? Thanks

**Comment by jmesny** [comment]
Considering the above example, here are the results of a call to`org.pac4j.saml.credentials.SAML2Credentials#getAttributes`.

5.1.0:
```json
[
    { "name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname", "attributeValues": [ "John" ] },
    { "name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname", "attributeValues": [ "DOE" ] },
    { "name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress", "attributeValues": [ "jdoe@company" ] },
    { "name": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role", "attributeValues": [ "..." ] },
]
```

5.1.1:
```json
[
    { "name": "AttributeValue", "attributeValues": [ "John" ] },
    { "name": "AttributeValue", "attributeValues": [ "DOE" ] },
    { "name": "AttributeValue", "attributeValues": [ "jdoe@company" ] },
    { "name": "AttributeValue", "attributeValues": [ "..." ] },
]
```

I will try to provide a fix.

**Comment by leleuj** [comment]
Thanks. I should release a version 5.1.2 very soon.

**Comment by salk31** [comment]
Sorry if this is the wrong place to comment, I couldn't find where to raise a possible bug and reference this.

With delegated auth the SAML attribute I want is:
```
<saml2:AttributeValue xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
    <saml2:NameID
        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" 
        NameQualifier="https://umbrellaid.org/idp/shibboleth" 
        SPNameQualifier="https://XXXXXXX.ac.uk">
        XXXXXXXX
    </saml2:NameID>
</saml2:AttributeValue>
```
(dumped with XMLObjectSupport.marshallToOutputStream from the opensaml original)

With 5.1.4 used via CAS 6.5.0-RC2 it is getting translated to:
SAMLAttribute{friendlyName='null', name='NameID', nameFormat='null', attributeValues=[_private_]}

It was OK in the older version of CAS and also if I disable the "isComplex" behaviour in SAMLCredential.from

It seems like this change is mangling this? The IdP seems to be producing something in line with https://shibboleth.atlassian.net/wiki/spaces/SHIB2/pages/2577072511/NativeSPTargetedID 

Make any sense?

Regards

Sam

**Comment by leleuj** [comment]
Github issues have been removed due to lack of resulting contributions. Bugs can be discussed on the users mailing list: https://groups.google.com/g/pac4j-users

**Comment by salk31** [comment]
Hi Jérôme,

Sorry for coming back here to ask but I'm not sure what the next step is. I posted on the forum https://groups.google.com/g/pac4j-users/c/MN24ReMvW_E but no replies so far.

I'm up for trying to come up with a pull request but I don't know the domain or codebase well enough to jump straight to one design. Could the next step to be to try and get a core developer to approve some approach (in principal)?

Cheers

Sam

**Comment by leleuj** [comment]
I replied to you on the mailing list. The next step is to submit a PR.

**Pull request merged**
