### PR TITLE
Add equals / hashCode on credentials to make LocalCachingAuthenticator work

### PR DESCRIPTION
**Pull request by leleuj**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Looks great. Do we have apache commons to generate equals and hashCode? 

I also think we should enforce these two methods at the Credentials level. So extensions are forced to add them. It's too easy to forget and the compiler does not care.

**Comment by leleuj** [comment]
The `pac4j-http` module already depends on Guava and commons-codec, so I guess we could add the dependency on commons.

How do you want to enforce these two methods (I'm thinking of subclasses)? In `HttpCredentials` you mean?

**Comment by mmoayyed** [comment]
Yes, mark the both as abstract

**Comment by leleuj** [comment]
Updated pull.

**Comment by mmoayyed** [comment]
:+1:

**Pull request merged**
