### PR TITLE
Allow S3 client configuration to be customized for SP metadata

### PR DESCRIPTION
**Pull request by mmoayyed**
- Minor changes around how the new S3 metadata generator can be customized and built.
- Changing the default checksum strategy to CRC instead.

### CODE REVIEW

**Comment by mmoayyed** [comment]
This is done mainly because it seems like SHA256 requires some extra work by clients:

```
Caused by:
        software.amazon.awssdk.services.s3.model.S3Exception: Value for x-amz-checksum-sha256 header is invalid. (Service: S3, Status Code: 400, Request ID: 0da1350d-3dfb-4e3c-81ab-88270fff340a, Extended Request ID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=)
            at app//software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
            at app//software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
            at app//software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
            at app//software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
            at app//software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:93)
            at app//software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:279)
            at app//software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
            at app//software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
```

**Comment by mmoayyed** [comment]
@leleuj do you think you might be able to publish a 6.0.4.1 with this change? or would you rather wait?

**Comment by leleuj** [comment]
OK. I'm cutting a new v6.0.4.1 release...

**Comment by leleuj** [comment]
The release process is over. The artifacts will show up soon in the Maven central repository...

**Pull request merged**
