### PR TITLE
WIP: running all unit tests

### PR DESCRIPTION
**Pull request by leleuj**
I just realized that tests were not run if they end with "Test" and not "Tests".

### CODE REVIEW

**Comment by leleuj** [comment]
Doing that, a SAML test fails:

```java
pac4j test 08:44:01 [main] ERROR n.s.t.x.XMLSecTool - Unknown error
org.cryptacular.EncodingException: Key encoding error
	at org.cryptacular.asn.AbstractPrivateKeyDecoder.decode(AbstractPrivateKeyDecoder.java:31)
	at org.cryptacular.util.KeyPairUtil.decodePrivateKey(KeyPairUtil.java:411)
	at org.cryptacular.util.KeyPairUtil.decodePrivateKey(KeyPairUtil.java:376)
	at org.opensaml.security.crypto.KeySupport.decodePrivateKey(KeySupport.java:249)
	at org.opensaml.security.crypto.KeySupport.decodePrivateKey(KeySupport.java:202)
	at net.shibboleth.tool.xmlsectool.CredentialHelper.getFileBasedCredentials(CredentialHelper.java:79)
	at net.shibboleth.tool.xmlsectool.XMLSecTool.getCredential(XMLSecTool.java:889)
	at net.shibboleth.tool.xmlsectool.XMLSecTool.main(XMLSecTool.java:148)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.writeServiceProviderMetadataToResource(SAML2ServiceProviderMetadataResolver.java:148)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.prepareServiceProviderMetadata(SAML2ServiceProviderMetadataResolver.java:103)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.resolve(SAML2ServiceProviderMetadataResolver.java:157)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolverTest.resolveServiceProviderMetadata(SAML2ServiceProviderMetadataResolverTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: java.nio.BufferOverflowException: null
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapCharBuffer.put(HeapCharBuffer.java:169)
	at org.cryptacular.util.PemUtil.decode(PemUtil.java:117)
	at org.cryptacular.util.PemUtil.decode(PemUtil.java:90)
	at org.cryptacular.asn.AbstractPrivateKeyDecoder.tryConvertPem(AbstractPrivateKeyDecoder.java:47)
	at org.cryptacular.asn.AbstractPrivateKeyDecoder.decode(AbstractPrivateKeyDecoder.java:25)
	... 37 common frames omitted
```

The error starts with this change: https://github.com/pac4j/pac4j/commit/3806174df54b939ed2785ee493f63b9851fcd03e

Seeing the issue around metadata signature, I tried to sign the SP metadata in my test webapp and got the following error:

```java
java.security.cert.CertificateException: Certificate file /Users/jleleu/sources/spring-webmvc-pac4j-boot-demo/target/classes/saml-signing-cert.crt does not exist
	at org.opensaml.security.x509.X509Support.decodeCertificates(X509Support.java:302) ~[opensaml-security-api-3.4.0.jar:na]
	at net.shibboleth.tool.xmlsectool.CredentialHelper.getFileBasedCredentials(CredentialHelper.java:70) ~[xmlsectool-2.0.0.jar:na]
	at net.shibboleth.tool.xmlsectool.XMLSecTool.getCredential(XMLSecTool.java:889) [xmlsectool-2.0.0.jar:na]
	at net.shibboleth.tool.xmlsectool.XMLSecTool.main(XMLSecTool.java:148) [xmlsectool-2.0.0.jar:na]
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.writeServiceProviderMetadataToResource(SAML2ServiceProviderMetadataResolver.java:148) [pac4j-saml-3.6.0-SNAPSHOT.jar:na]
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.prepareServiceProviderMetadata(SAML2ServiceProviderMetadataResolver.java:103) [pac4j-saml-3.6.0-SNAPSHOT.jar:na]
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.resolve(SAML2ServiceProviderMetadataResolver.java:157) [pac4j-saml-3.6.0-SNAPSHOT.jar:na]
	at org.pac4j.saml.client.SAML2Client.initServiceProviderMetadataResolver(SAML2Client.java:178) [pac4j-saml-3.6.0-SNAPSHOT.jar:na]
	at org.pac4j.saml.client.SAML2Client.clientInit(SAML2Client.java:115) [pac4j-saml-3.6.0-SNAPSHOT.jar:na]
	at org.pac4j.core.client.IndirectClient.internalInit(IndirectClient.java:58) [pac4j-core-3.6.0-SNAPSHOT.jar:na]
	at org.pac4j.core.util.InitializableObject.init(InitializableObject.java:20) [pac4j-core-3.6.0-SNAPSHOT.jar:na]
	at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:93) [pac4j-core-3.6.0-SNAPSHOT.jar:na]
```

I can't even find the certificate file.

@mmoayyed does it work for you?

**Comment by mmoayyed** [comment]
Could you push your changes to a branch of this repo so I can run the same stuff?

**Comment by leleuj** [comment]
Here is the branch where I enabled all the tests: https://github.com/pac4j/pac4j/pull/1270
and I have one SAML failing test related to the SP metadata signature:

```java
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.pac4j.saml.metadata.SAML2IdentityProviderMetadataResolverTest
[INFO] Running org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolverTest
pac4j test 19:23:42 [main] ERROR n.s.t.x.XMLSecTool - Unknown error
org.cryptacular.EncodingException: Key encoding error
	at org.cryptacular.asn.AbstractPrivateKeyDecoder.decode(AbstractPrivateKeyDecoder.java:31)
	at org.cryptacular.util.KeyPairUtil.decodePrivateKey(KeyPairUtil.java:411)
	at org.cryptacular.util.KeyPairUtil.decodePrivateKey(KeyPairUtil.java:376)
	at org.opensaml.security.crypto.KeySupport.decodePrivateKey(KeySupport.java:249)
	at org.opensaml.security.crypto.KeySupport.decodePrivateKey(KeySupport.java:202)
	at net.shibboleth.tool.xmlsectool.CredentialHelper.getFileBasedCredentials(CredentialHelper.java:79)
	at net.shibboleth.tool.xmlsectool.XMLSecTool.getCredential(XMLSecTool.java:889)
	at net.shibboleth.tool.xmlsectool.XMLSecTool.main(XMLSecTool.java:148)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.writeServiceProviderMetadataToResource(SAML2ServiceProviderMetadataResolver.java:155)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.prepareServiceProviderMetadata(SAML2ServiceProviderMetadataResolver.java:110)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.resolve(SAML2ServiceProviderMetadataResolver.java:164)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolverTest.resolveServiceProviderMetadata(SAML2ServiceProviderMetadataResolverTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: java.nio.BufferOverflowException: null
```

**Comment by mmoayyed** [comment]
Thanks, but that seems to be a branch to your fork. Could you push to a branch here? I'd prefer to not fork/clone yours.

**Comment by leleuj** [comment]
Here we go: https://github.com/pac4j/pac4j/pull/1271, branch: `test-3x`...

**Pull request merged**
