### PR TITLE
Fix pac4j-saml tests; open up SAML client for extensions

### PR DESCRIPTION
**Pull request by mmoayyed**
Changes here are already included in #1804

### CODE REVIEW

**Comment by mmoayyed** [comment]
Also note that this PR enables GH Actions for this branch. (Taken from master)

**Comment by leleuj** [comment]
Yes, I want to trigger the GH actions on the PRs too...

**Comment by mmoayyed** [comment]
This should be mergeable, yes? Are the CI failures based on Github Actions relevant?

**Comment by leleuj** [comment]
The failures don't seem to be relevant (for now). Merging...

**Pull request merged**
