### PR TITLE
Problem: Saml2Credential should be serializable 

### PR DESCRIPTION
**Pull request by mmoayyed**
- Ensures that all classes that are marked as serializable are assigned an ID
- Modified the SAML2Credential class to not use native SAML2 objects that are not serializable; instead provides wrapper classes to hold the same data-set accessed by pac4j today.
- Add test cases for above.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Do not merge yet. Need to run some sanity tests against an IDP.

**Comment by mmoayyed** [comment]
Tested. All works as expected.

**Comment by leleuj** [comment]
I tested it and it works properly. Merging

**Comment by leleuj** [comment]
Do you plan to merge: https://github.com/pac4j/pac4j/pull/1171 before the 3.1.0 release?

**Comment by mmoayyed** [comment]
Yes, I think we should.

**Comment by leleuj** [comment]
I just cut the release (3.1.0), it will show up in the Maven central repo in a few hours...

**Pull request merged**
