### PR TITLE
SAML support is broken due to the use of the J2EContext

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes https://github.com/pac4j/pac4j/issues/219

### CODE REVIEW

**Comment by mmoayyed** [comment]
So this pull removes the use of J2EContext in favor of WebContext. For SAML, additional encoders/decoders are provided that work based on WebContext rather than the native http request and response. The WebContext itself is modified to handle response-related functions a bit more. All tests should pass for SAML. (I ended up updating our metadata on testshib, by the filename `pac4j-sp-metadata.xml`)

**Comment by leleuj** [comment]
Great! Do you want me to test it or just review the source code?

**Comment by mmoayyed** [comment]
It would be great if you could do both. Certainly testing it with the demo app you had that demonstrated the problem would be nice.

**Comment by leleuj** [comment]
:+1:

I'll make a real test tomorrow.

**Comment by leleuj** [comment]
Successfully tested!

**Comment by mmoayyed** [comment]
parfait!

**Pull request merged**
