### PR TITLE
Expose HttpServletRequest's request url for web context

### PR DESCRIPTION
**Pull request by mmoayyed**
Avoids casting down to JEEContext.

### CODE REVIEW

**Comment by leleuj** [comment]
OK. I understand.
There is a problem though: this is a breaking change and this cannot be done for a minor version.

Hopefully, we can workaround that problem: can you propose a default implementation of `getRequestURL` in the `WebContext` interface which just removes the query string from the `getFullRequestURL` method if it exist (like you do in `MockWebContext`)?
Thanks

**Comment by mmoayyed** [comment]
Sure. Will do.

**Comment by mmoayyed** [comment]
This is done.

PS I will also be posting a new PR shortly to support SAML2 Scoping in authentication requests.

**Comment by leleuj** [comment]
Two last points:
- with the default implementation of `getRequestURL` in the `WebContext`, do you still need an implementation in `JEEContext`?
- can you drop a line in the release notes?

**Comment by mmoayyed** [comment]
I updated the release notes.

I think it's safest for the `JEEContext` to override the default implementation, since it delegates to the *real* request, and real implementations might want to handle this scenario differently. I wouldn't want to interfere with that.

**Comment by leleuj** [comment]
OK. Thanks

**Pull request merged**
