### PR TITLE
port saml changes over to master branch

### PR DESCRIPTION
**Pull request by mmoayyed**
Porting #1802 to master.

### CODE REVIEW

**Comment by leleuj** [comment]
I'm working on migrating from Travis to Github actions. You have 1 PMD violation ;-)

**Comment by mmoayyed** [comment]
Darn! Thanks, I'll fix it. I suppose I can connect IDEA to use the PMD plugin to catch these, right?

**Comment by leleuj** [comment]
Good question. I just run the build to perform the PMD check, but I suppose yes...

**Comment by mmoayyed** [comment]
Should be fixed now, I hope.

By the way kudos on GH actions. Side suggestion: let's make sure deploy depends on build. Otherwise broken stuff might get published.

**Comment by leleuj** [comment]
Yes, I realized my mistake on the missing dependency between my two jobs.

It works so much better than Travis... for now...

**Pull request merged**
