### PR TITLE
Added ability to make authnRequestSigned configurable

### PR DESCRIPTION
**Pull request by thinh76**

### CODE REVIEW

**Comment by leleuj** [comment]
+1

@mmoayyed : ok for you?

**Comment by mmoayyed** [comment]
Yes this is fine. @thinh76 You really ought to fix the indentation though. See the diff.

**Comment by thinh76** [comment]
Sorry @mmoayyed, I wanted to... but I saw indentation are different in a lot of files, and I thought we should have a format.xml or something so each contributors can import and apply the same styles... when I did the format using IDEA, it caused more differences than without formatting. BTW, do you still wait for me to submit format changes?

**Comment by leleuj** [comment]
Not a big deal, I will merge "as is" to cut the release...

**Pull request merged**
