### PR TITLE
Redirect url into AJAX query

### PR DESCRIPTION
**Pull request by andreaTP**
I backported the fix already agreed and merged on `master`, would you mind to publish a maintenance release (i.e. `1.9.8` ) integrating this fix?

Thanks a lot in advance

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks. Let's schedule the 1.9.8 version for the 6th June. Ping me if I forget.

**Comment by andreaTP** [comment]
Thank you, but, could I ask if is possible to release earlier, this is a pre-requisite for me for adding oidc integration to apache/zeppelin project (i.e. cannot have a PR there until this is published).
Thanks in advance.

**Comment by leleuj** [comment]
I just performed the 1.9.8 release, it should show up in the Maven central repository in a few hours...

**Comment by leleuj** [comment]
Notice that I'll plan to soon upgrade buji-pac4j (v3) to pac4j v2...

**Comment by andreaTP** [comment]
really, really helpful!!! Thanks a lot! and thanks for all the work with these libs! awesome! :-)

**Pull request merged**
