### PR TITLE
Fix for issue #979

### PR DESCRIPTION
**Pull request by fmartelli**
Handling AttributeConsumingServiceIndex into AuthnRequest

### CODE REVIEW

**Comment by mmoayyed** [comment]
Excellent work. Thank you.

**Comment by leleuj** [comment]
The change is fairly straightforward, but please try to think about updating the documentation next time (http://www.pac4j.org/docs/contribute.html#2-documentation).

**Comment by fmartelli** [comment]
Hi Jerome, thank you for the feedback.
Next time I'll take care of the documentation as well.
Regards


Il 6 settembre 2017 17:52:06 CEST, "LELEU Jérôme" <notifications@github.com> ha scritto:
>The change is fairly straightforward, but please try to think about
>updating the documentation next time
>(http://www.pac4j.org/docs/contribute.html#2-documentation).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pac4j/pac4j/pull/980#issuecomment-327528374

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by mmoayyed** [comment]
Updated docs.

**Comment by leleuj** [comment]
Excellent! Thanks

**Pull request merged**
