### PR TITLE
Account registration + linking

### LINKED ISSUE #339: Account registration
We certainly need a `ProfileWriter` for `LdapProfile`, `MongoProfile`... to create user accounts.

### PR DESCRIPTION
**Pull request by leleuj**
Closes #339 #342 #777

### CODE REVIEW

**Comment by AzureusNation** [comment]
Fantastic 👍 Just one question. Will this all work with postgresql?

**Comment by leleuj** [comment]
Yes, the `DbProfileService` should work with any SQL database. Though, you may need to update the example given for the creation of the `users` table.

**Comment by outkaj** [comment]
Hi @leleuj - is there any support for integrating pac4j with non-SQL databases such as LevelDB? Thanks so much!

**Comment by leleuj** [comment]
Yes, we support MongoDB and CouchDB: http://www.pac4j.org/docs/authenticators.html and we could support a lot more...

**Pull request merged**
