### PR TITLE
Merge attributes #1145

### PR DESCRIPTION
**Pull request by lrozenblyum**
Implements #1145

### CODE REVIEW

**Comment by leleuj** [comment]
Can you make this behavior configurable? I'm not so sure about where this change should go: the `UserProfile`, the `ProfileHelper`? ...

**Comment by lrozenblyum** [comment]
I'll check how to make it configurable (and first I need to fix checkstyle :) )

**Comment by lrozenblyum** [comment]
I'll check how to make it configurable (after checkstyle passes)

**Comment by leleuj** [comment]
Looks good to me. I'll change the version to 3.1.0 before the merge.

One last thing: can you add some documentation for that feature in the following page: https://github.com/pac4j/pac4j/blob/master/documentation/docs/user-profile.md and enhance the release notes as well: https://github.com/pac4j/pac4j/blob/master/documentation/docs/release-notes.md ?

Read this to know how to browse the documentation locally: https://github.com/pac4j/pac4j/tree/master/documentation

**Comment by lrozenblyum** [comment]
I've updated the profile documentation and the release notes @leleuj. Please take a look at the pull request

**Comment by leleuj** [comment]
Excellent! Will merge once I upgrade to version 3.1.0 (I likely need to release a v3.0.1 first with a bug fix).

**Comment by lrozenblyum** [comment]
Thanks! @leleuj

**Pull request merged**
