### PR TITLE
Initialize CAS logout by default

### PR DESCRIPTION
**Pull request by leleuj**

### CODE REVIEW

**Comment by leleuj** [comment]
To be updated after https://github.com/pac4j/pac4j/pull/347 is merged

**Comment by mmoayyed** [comment]
:+1: `InitializableWebObject` makes good sense here.

**Comment by leleuj** [comment]
Updated based on `InitializableWebObject`. Ready for merge.

**Comment by leleuj** [comment]
Merging this little one.

**Pull request merged**
