### PR TITLE
Fix class cast exception when validating assertion signatures.

### LINKED ISSUE #306: pac4j-saml: Typecast error in SAML2DefaultResponseValidator
There is a typecast error in SAML2DefaultResponseValidator.validateAssertionSignature().
Look at the following lines:
```java
     final QName role = selfContext.getRole();
        if (signature != null) {
            final String entityId = peerContext.getEntityId();
            validateSignature(signature, entityId, engine);
        } else if (((SPSSODescriptor) role).getWantAssertionsSigned()
                && !peerContext.isAuthenticated()) {
            throw new SAMLException("Assertion or response must be signed");
        }
```
The cast of role to SPSSODescriptor is not valid. Role is of type QName and QName does not have any common part of hierarchy with SPSSODescriptor.

Once the execution gets to the else-if condition (if the signature is null), this code will crash. This stacktrace is from 1.7.1 but valid for 1.8.x too:
```
Caused by: java.lang.ClassCastException: javax.xml.namespace.QName cannot be cast to org.opensaml.saml.saml2.metadata.SPSSODescriptor
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAssertionSignature(SAML2DefaultResponseValidator.java:659)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAssertion(SAML2DefaultResponseValidator.java:400)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateSamlSSOResponse(SAML2DefaultResponseValidator.java:307)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validate(SAML2DefaultResponseValidator.java:151)
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageReceiver.receiveMessage(SAML2WebSSOMessageReceiver.java:83)
	at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.receive(SAML2WebSSOProfileHandler.java:54)
	at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:253)
	at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:77)
	at org.pac4j.core.client.BaseClient.getCredentials(BaseClient.java:222)
	at org.jasig.cas.support.pac4j.web.flow.ClientAction.doExecute(ClientAction.java:196)
	at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188) 
	at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51) 
	... 50 common frames omitted 
```

I only have limited knowledge of OpenSaml but I think we should first find a RoleDescriptor for the QName and then call getWantAssertionsSigned() on it.

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #306

### CODE REVIEW

**Comment by mmoayyed** [comment]
@jkacer will you be able to test and confirm the fix here?

**Comment by leleuj** [comment]
Thanks. Will merge.

@jkacer : do you think you'll be able to test it before tomorrow (release day)? Thx

**Comment by jkacer** [comment]
Hi, unfortunately not :-(
We only have a single IdP that doesn't send the signature and this code cannot get to our SP that is set up against it (there is 1.7.1 fixed by us).
I can play with our local Shibboleth and switch signatures off (if it is possible at all - I'll have to investigate) but it won't be before Thursday.
I am sorry, guys.

**Comment by leleuj** [comment]
No problem. Do your best. Thanks for testing. I'm stuck on my side on this: https://github.com/pac4j/pac4j/issues/297. So I'll certainly delay the release to next week.

**Comment by jkacer** [comment]
Thank you, it will give me some time. I'll report the result as soon as I test it.

**Comment by leleuj** [comment]
@jkacer : any feedback on this? Thanks

**Comment by jkacer** [comment]
@leleuj Not so far, sorry...

**Comment by jkacer** [comment]
So, the full 1.8.0-RC2-SNAPSHOT cannot be tested because my CAS does not compile against it anymore; there is 1 compilation failure in cas-server-support-pac4j.

But I will try to put this change into 1.7.1 and test.

**Comment by leleuj** [comment]
What's the compilation failure?

**Comment by jkacer** [comment]
The change, applied to 1.7.1, seems OK, although I think I did not really test it.

I used the following piece settings for our Shibboleth's relying-party.xml:
```
<rp:ProfileConfiguration xsi:type="saml:SAML2SSOProfile" includeAttributeStatement="true" 
                            assertionLifetime="PT5M" assertionProxyCount="0" 
                            signResponses="never" signAssertions="never" 
                            encryptAssertions="never" encryptNameIds="never"
                            includeConditionsNotBefore="true"/>
```
but the SAML response coming from it are still signed :-( Most likely because the SP metadata contains a flag asking for signed responses:
```
10:22:38.567 - DEBUG [edu.internet2.middleware.shibboleth.idp.profile.saml2.AbstractSAML2ProfileHandler:653] - IdP relying party configuration 'default' indicates to sign assertions: false
10:22:38.567 - DEBUG [edu.internet2.middleware.shibboleth.idp.profile.saml2.AbstractSAML2ProfileHandler:660] - Entity metadata for relying party 'urn:idc:authentication:saml2:entity:cas:local:idcshibdev 'indicates to sign assertions: true
10:22:38.567 - DEBUG [edu.internet2.middleware.shibboleth.idp.profile.saml2.AbstractSAML2ProfileHandler:583] - Determining signing credntial for assertion to relying party 'urn:idc:authentication:saml2:entity:cas:local:idcshibdev'
10:22:38.567 - DEBUG [edu.internet2.middleware.shibboleth.idp.profile.saml2.AbstractSAML2ProfileHandler:599] - Signing assertion to relying party urn:idc:authentication:saml2:entity:cas:local:idcshibdev
```
So I think this can only be tested with IdPs that disregard the WantAssertionsSigned flag in metadata or if the flag is false. We have "true" in our metadata, testing with "false" will require some more time. But I can do that.

**Comment by jkacer** [comment]
@leleuj The compilation error is inside ClientAction, method prepareForLoginPage():
```
final String redirectionUrl = baseClient.getRedirectionUrl(webContext);
```
getRedirectionUrl() is not defined for the type BaseClient.

But I am still at v. 4.0.0. It might have been rewritten in CAS 4.0.x or CAS 4.1.x.

**Comment by leleuj** [comment]
The `getRedirectionUrl()` is only available in the `IndirectClient` so you must certainly change the cast...

**Comment by jkacer** [comment]
Finally I'm getting unsigned responses from Shibboleth.
When the fix is applied onto 1.7.1, it crashes on NullPointerException:
```
Caused by: java.lang.NullPointerException: null
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAssertionSignature(SAML2DefaultResponseValidator.java:662)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAssertion(SAML2DefaultResponseValidator.java:400)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateSamlSSOResponse(SAML2DefaultResponseValidator.java:307)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validate(SAML2DefaultResponseValidator.java:151)
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageReceiver.receiveMessage(SAML2WebSSOMessageReceiver.java:83)
	at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.receive(SAML2WebSSOProfileHandler.java:54)
	at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:253)
	at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:1)
	at org.pac4j.core.client.BaseClient.getCredentials(BaseClient.java:222)
	at org.jasig.cas.support.pac4j.web.flow.ClientAction.doExecute(ClientAction.java:196)
	at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188)
	at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51)
	... 50 common frames omitted
```
Line 662 is the line with the modification. So either getSPSSODescriptor() or getWantAssertionsSignedXSBoolean() returns null. A check for null would probably help here. And maybe getWantAssertionsSigned() instead of getWantAssertionsSignedXSBoolean() - but I don't know what the difference is.

**Comment by mmoayyed** [comment]
I wasn't able to locate a `getWantAssertionsSigned()` in the new API. Do you know where that might be? Otherwise, a null-check sounds fine. Could you issue the PR?

**Comment by jkacer** [comment]
Misagh, it's in interface SPSSODescriptor in OpenSaml. Both methods are in the same interface, lines 84+91.
Library opensaml-saml-api-3.1.1.

**Comment by jkacer** [comment]
And before a PR, I will also try the full 1.8.0 with the cast proposed by Jerome.

**Comment by mmoayyed** [comment]
Excellent. I am around to review the changes.

**Comment by mmoayyed** [comment]
I should add, if you are working on adding 1.8 to CAS, we could definitely use your help with the CAS project with another PR. So one PR here to fix this issue and another for CAS to upgrade to 1.8 would be very very appreciated.

**Comment by leleuj** [comment]
@jkacer : sorry for the "pressure" (I have received several emails about the release date), but what's the status on this? How can I help you?

**Comment by jkacer** [comment]
@leleuj Hi! Sorry, I didn't work on it during the weekend. If you want to release 1.8.0 asap, just go on, I don't insist on having a fix for this bug in this version.
I'm going to try if 1.8.0 crashes on NPE too, then I'll try to add some checks for null and submit a PR.

**Comment by jkacer** [comment]
Just FYI, I'm getting a NPE with 1.8.0 RC2 too.

**Comment by leleuj** [comment]
No problem at all. If you can fix in the next few days (before Thursday I would say), I'll wait. Otherwise I'll cut the release and we'll fix that in the 1.8.1.

When do you think you'll be able to submit the PR?

**Comment by jkacer** [comment]
I've just done it, please see my comments on the issue page...

**Comment by leleuj** [comment]
@jkacer : are you working on the pac4j upgrade in the CAS server? Because I planned to start working on that tomorrow...

**Comment by jkacer** [comment]
Hi! No, I'm not working on it. Please go on, you will be 100 times faster than me. Moreover, I'm still on CAS 4.0.x.

**Comment by leleuj** [comment]
Copy that

**Pull request merged**
