### PR TITLE
[WIP] extend CouchDb support

### PR DESCRIPTION
**Pull request by tduehr**
allows automatic generation of design doc and uses JSON serialization

By extension, this also simplifies use.

### CODE REVIEW

**Comment by leleuj** [comment]
The version 3.0.0 has been released, so it will be merged in version 3.1.0.

**Comment by tduehr** [comment]
How much backwards compatibility would you like in it for a minor version release like that?

**Comment by leleuj** [comment]
You should be able to upgrade from v3.0.0 and v3.1.0 without any compilation or runtime issue...

**Comment by tduehr** [comment]
Looks like I can set it up to silently update access methods as records are accessed and saved. That work?

**Comment by tduehr** [comment]
Just need to add tests specific to this code...

**Comment by leleuj** [comment]
@tduehr I'm not sure to understand your previous comment...

**Comment by leleuj** [comment]
@tduehr do you plan to complete and merge this PR? Or do we close it?

**Comment by leleuj** [comment]
Closed due to inactivity. Feel free to reopen when necessary.

**Pull request closed without merging**
