### PR TITLE
fix public api

### PR DESCRIPTION
**Pull request by andreaTP**
Unfortunately during this cherry pick I managed to break the public API, this is a fix for the error.

### CODE REVIEW

**Comment by leleuj** [comment]
I guess we'll need a 1.9.9 version just after merging that, won't we?

**Comment by andreaTP** [comment]
Yes, this time not in a hurry for me, since I already have a proper release.
Probably some "release notes are needed", sorry for the inconvenience.

**Comment by leleuj** [comment]
Yes, maybe, I'll even skip the 1.9.8 in the release notes. Sometimes, one release is a failure...

**Comment by leleuj** [comment]
We have the same issue for version 2.1.0. Since v2.0.0, we user semver so v2.1.0 should be backwards compatible with v2.0.0. Can you push the same fix for the master? Thanks

**Comment by leleuj** [comment]
Thinking about that a little more, I don't think the method should be marked as `Deprecated`. I'll change that.

**Comment by leleuj** [comment]
I'm releasing the 1.9.9 version...

**Pull request merged**
