### PR TITLE
Using HTTP-POST binding with signing causes UninitializedComponentException

### PR DESCRIPTION
**Pull request by fbusselgln**
Hello everyone! This unit test shows there is a problem in pac4j-saml. The message encoder is initialized in line 85, but is already used in line 82 when using a HTTP-POST binding along with authn signing: https://github.com/pac4j/pac4j/blob/9afab79fe48d54be388c382a775421935541d3a6/pac4j-saml/src/main/java/org/pac4j/saml/profile/impl/AbstractSAML2MessageSender.java#L82

I'm not sure how to fix this best. Do you have any suggestions?

### CODE REVIEW

**Comment by leleuj** [comment]
I don't understand: the build passes.

**Comment by fbusselgln** [comment]
Interesting, I was able to prove the behaviour on commit 46f57b5fd, but after merging the current master into my branch, the behaviour is gone. 6.0.0-RC6 is also affected (commit cda120c). Copying the unit test into RC6 will let it fail with the exact same exception:

`
org.pac4j.saml.exceptions.SAMLException: net.shibboleth.shared.component.UninitializedComponentException: Unidentified Component has not yet been initialized and cannot be used.

	at org.pac4j.saml.profile.impl.AbstractSAML2MessageSender.invokeOutboundMessageHandlers(AbstractSAML2MessageSender.java:153)
	at org.pac4j.saml.profile.impl.AbstractSAML2MessageSender.sendMessage(AbstractSAML2MessageSender.java:82)
	at org.pac4j.saml.redirect.SAML2RedirectionActionBuilder.getRedirectionAction(SAML2RedirectionActionBuilder.java:46)
	at org.pac4j.core.client.IndirectClient.getRedirectionAction(IndirectClient.java:136)
	at org.pac4j.saml.client.PostSAML2ClientTests.testPostDestinationBindingWithRequestSignedWorks(PostSAML2ClientTests.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)`

Seems like it got fixed 5 days ago. https://github.com/pac4j/pac4j/commit/f7e41c942781663dac6bff4f1a29f4cab6006207

Anyway, the unit test might come in handy to make sure this doesn't happen again. :-)

**Comment by leleuj** [comment]
Yes, it was fixed. Merging to confirm the behavior.

**Comment by fbusselgln** [comment]
Are there any plans for a new release candidate any time soon? This is quite a blocker for us, but i would very much favor using version 6 over version 5, as it works just fine except for this issue.

**Comment by leleuj** [comment]
I just cut the v6.0.0-RC7 release. It will show up in the Maven central repo within a few minutes/hours...

**Pull request merged**
