### PR TITLE
Fix integration tests for Pac4j

### PR DESCRIPTION
**Pull request by JacobASeverson**

### CODE REVIEW

**Comment by JacobASeverson** [comment]
@leleuj Is the testscribeup Github account still have the Gravatar set up? The `GithubClientIT` test is failing because the gravatar id comes back null and the account picture seems to be blank.

**Comment by leleuj** [comment]
Providers (often) change the data they return so sometimes attribute names change or data are not returned any more. I recommend you turn DEBUG logs on org.pac4j to see the JSON response returned by the provided to see it the gravatar is still somewhere in the response...

**Comment by leleuj** [comment]
Any update on this?

**Comment by mmoayyed** [comment]
:+1:

**Comment by leleuj** [comment]
I'm not sure all tests have been fixed but we can already merged this one. And someone else (at worst me) can restart a new PR on this.

@JacobASeverson : how do you feel on this?

**Comment by JacobASeverson** [comment]
Good idea :+1:

**Comment by leleuj** [comment]
OK. Merging this PR, but the issue is still open.

**Pull request merged**
