### PR TITLE
Resolving concurrency issue in SAML2IdentityProviderMetadataResolver -Closes #290

### LINKED ISSUE #290: Concurrency issue in SAML2IdentityProviderMetadataResolver
I am building a SAML SP using pac4j and in the load tests, found that whenever  saml2client is shared across requests , the following exception is intermittently seen in the logs.

net.shibboleth.utilities.java.support.component.UninitializedComponentException: Component 'org.opensaml.saml.metadata.resolver.impl.DOMMetadataResolver' has not yet been initialized and cannot be used.

at net.shibboleth.utilities.java.support.component.ComponentSupport.ifNotInitializedThrowUninitializedComponentException(ComponentSupport.java:106)

at org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver.resolveSingle(AbstractMetadataResolver.java:164)

at org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver.resolveSingle(AbstractMetadataResolver.java:62)

at org.pac4j.saml.metadata.SAML2IdentityProviderMetadataResolver.getEntityDescriptorElement(SAML2IdentityProviderMetadataResolver.java:171)

at org.pac4j.saml.metadata.SAML2IdentityProviderMetadataResolver.getEntityId(SAML2IdentityProviderMetadataResolver.java:143)

at org.pac4j.saml.context.SAML2ContextProvider.addContext(SAML2ContextProvider.java:143)

at org.pac4j.saml.context.SAML2ContextProvider.addIDPContext(SAML2ContextProvider.java:134)

at org.pac4j.saml.context.SAML2ContextProvider.buildContext(SAML2ContextProvider.java:97)

at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:247)

at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:76)

at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:187)

On looking at the possible reason, I built a local version of pac4j-saml, by making the field idpMetadataProvider, a local var in the resolve method.

My tests show that this resolves the issue seen and concurrent requests for SAML request generation / assertion processing works fine.

### PR DESCRIPTION
**Pull request by jayaramsankara**
Making the class thread safe since concurrent request to retreiving the user profile while processing the saml assertion was resulting in concurrency issues. 

See issue #290

### CODE REVIEW

**Comment by mmoayyed** [comment]
:+1:

**Comment by mmoayyed** [comment]
Just a tip: If you include the text "Closes https://github.com/pac4j/pac4j/issues/290" in the PR description, when the PR is merged the issue is auto closed :) Might help later on. 

Thanks again.

**Comment by jayaramsankara** [comment]
This is not an optimal solution - it has performance impact since every call to resolve will result in IDP metadata being processed.  Will push further changes to optimise this.  I see that Saml2Client::internalInit does initialise the resolver which in turn calls resolve.

So I am thinking of adding a condition where idpmetadataprovider is checked for null and if its resolve proceeds, else returns the already resolved one. 

If (idpMetadataProvider != null) {
  return idpMetadataProvider;
}

What do you think?

**Comment by jayaramsankara** [comment]
I did load tests with the current fix as well the  new changes I intended to make and I do not see any performance improvement.  So I think, I will leave the changes as it is - just making the metadataprovider a local var.

If changes look ok, please merge the PR .

**Comment by leleuj** [comment]
Looks good to me thanks to the comprehensive comment.

**Pull request merged**
