### PR TITLE
Let properties factory handle different oidc client types.

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #661

### CODE REVIEW

**Comment by leleuj** [comment]
Oops! Looks like there is a miscommunication: https://github.com/pac4j/pac4j/pull/661

**Comment by leleuj** [comment]
You mean "Cloes #656"?

**Comment by leleuj** [comment]
This PR "duplicates": #661 for #656, doesn't it?

**Comment by mmoayyed** [comment]
Ah cool! I didnt even see that one :D glad you got to it.

**Comment by leleuj** [comment]
Can I merge #661 ?

**Comment by mmoayyed** [comment]
Of course. Please proceed.

**Pull request closed without merging**
