### PR TITLE
Only bootstrapping signature signing configuration if none defined

### PR DESCRIPTION
**Pull request by luis100**
Before submitting any pull request, please read the contribution guide: http://www.pac4j.org/docs/contribute.html

### CODE REVIEW

**Comment by leleuj** [comment]
You need to sync with master and please don't format all your source code (just your changes), I'm totally unable to validate the changes you propose.

**Comment by luis100** [comment]
Yes, I'll do that. Give me a week to finish my changes, I'll ensure I fix the formatting.

**Comment by leleuj** [comment]
No problem. No hurry.

**Comment by leleuj** [comment]
@luis100 are we good on this? don't forget the PR for the master?

**Comment by luis100** [comment]
Working on the integration with the [European e-Identification](https://ec.europa.eu/digital-single-market/en/e-identification), specifically with [Portuguese implementation](https://www.autenticacao.gov.pt/), created the need for new changes, that will be bundled as a single PR, for 2.2.0 and for master.

Will close this PR can create the two new ones that superseed this.

**Comment by luis100** [comment]
Created pull requests https://github.com/pac4j/pac4j/pull/1127 and https://github.com/pac4j/pac4j/pull/1128

**Pull request closed without merging**
