### PR TITLE
Add support for linkedin client via properties. Add support for oidc scope

### PR DESCRIPTION
**Pull request by mmoayyed**

### CODE REVIEW

**Comment by mmoayyed** [comment]
https://github.com/apereo/cas/issues/2101

**Comment by leleuj** [comment]
As a matter of facts, the master is version 2.0.0 but you can certainly backport this change on the 1.9.x branch, for version 1.9.5 (1.9.4 was a security fix).

**Comment by mmoayyed** [comment]
Gotcha. Sure I can backport

**Comment by mmoayyed** [comment]
Actually, decided to not do this unless there is a request by someone to get the behavior into the 1.9.x line. We are going to switch to 2.0.0-SNAPSHOT soon which will hopefully ship with CAS 5.1 anyway.

**Comment by leleuj** [comment]
OK. No problem.

**Pull request merged**
