### PR TITLE
Add the ability for preferredJwsAlgorithm to be set via shiro.ini.

### PR DESCRIPTION
**Pull request by minfrin**
At the moment, the preferredJwsAlgorithm is a JWSAlgorithm, which cannot be instantiated from shiro.ini.

Add a String setting method that can be used by javabeans code.

### CODE REVIEW

**Comment by minfrin** [comment]
Would it be possible to backport this to v3.6.x?

**Comment by leleuj** [comment]
Thanks for your contribution. Will backport.

**Comment by leleuj** [comment]
Done on 3.7.x.

**Comment by minfrin** [comment]
Thank you for this, I appreciate it.

**Pull request merged**
