### PR TITLE
add sql index in doc

### LINKED ISSUE #903: index on the sql backend
The [doc for sql](http://www.pac4j.org/docs/authenticators/sql.html) currently only states to create a table. In my experience, creating indexes on the fields that will be queried significantly improves performance. Looking at the code, I think asking users to also run

```sql
ALTER TABLE `users` ADD UNIQUE KEY `username` (`username`), ADD UNIQUE KEY `linkedid` (`linkedid`);
```

would be helpful (removing the `UNIQUE` keyword if entries are not supposed to be unique). I can't really test though.

### PR DESCRIPTION
**Pull request by eroux**
This fixes #903. This is not tested though, we don't use sql.

### CODE REVIEW

**Comment by leleuj** [comment]
This won't work in fact, the PR should target the master and this file: https://github.com/pac4j/pac4j/blob/master/documentation/docs/authenticators/sql.md

In the build process, they are copied to the gh-pages branch: https://github.com/pac4j/pac4j/blob/master/.travis.yml#L21

**Comment by eroux** [comment]
Ok, maybe a CONTRIBUTING.md would help?

**Comment by leleuj** [comment]
Yes, I keep that on mind.

**Comment by leleuj** [comment]
Here it is: https://github.com/pac4j/pac4j/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
