### PR TITLE
Use callbackUrlResolver to compute URL for loginUrl.

### PR DESCRIPTION
**Pull request by jonathanlabin**
#552

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks. Can you submit the same update for the master?

**Comment by leleuj** [comment]
@jonathanlabin : can you submit the same pull request for master? Thanks.

**Comment by jonathanlabin** [comment]
Sorry this fell through the cracks.  Am I reading github correctly that you applied the equivalent change to master yourself?  If not, I'll be happy to do it.

**Comment by leleuj** [comment]
Yes, I re-applied your changes on the master... everything's ok... Thanks for checking.

**Pull request merged**
