### PR TITLE
Improved JWT support

### PR DESCRIPTION
**Pull request by leleuj**

### CODE REVIEW

**Comment by mmoayyed** [comment]
What are we doing here exactly?

**Comment by leleuj** [comment]
I sumitted the PR too early. Updating the JWT support to meet https://github.com/Jasig/cas/issues/1387

**Comment by mmoayyed** [comment]
Ah, right on! :)

**Comment by leleuj** [comment]
Ready for review. Pre-requisite of: https://github.com/Jasig/cas/pull/1393

**Comment by mmoayyed** [comment]
Posted a few comments. Will resume the review once pac4j merges. Thanks for taking this on :)

**Comment by leleuj** [comment]
OK. Merging this one...

**Comment by tovbinm** [comment]
@leleuj good start. why `exp` (Expiration Time) is not handled?

**Comment by leleuj** [comment]
Yes, it could / should be handled. Generally, I'm waiting for feedbacks to know what features are expected.

Feel free to open a new issue (and submit a pull request).

**Comment by tovbinm** [comment]
Thanks. I just rewrote it in Scala. I'll try to make a similar change for
the pac4j as well.

On Thursday, February 18, 2016, LELEU Jérôme <notifications@github.com>
wrote:

> Yes, it could / should be handled. Generally, I'm waiting for feedbacks to
> know what features are expected.
>
> Feel free to open a new issue (and submit a pull request).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pac4j/pac4j/pull/417#issuecomment-185626000>.
>


-- 


-Matthew

**Comment by leleuj** [comment]
Thanks. BTW, what's the reason behind the rewrite in Scala?

**Comment by tovbinm** [comment]
@leleuj no particular reason, except that that's my language of choice and it's overall shorter.

**Pull request merged**
