### PR TITLE
Integrate Checkstyle for style checks (Issue #955)

### PR DESCRIPTION
**Pull request by tianyin**
This PR integrates CheckStyle using `maven-checkstyle-plugin` (added in `pom.xml`).

I create two CheckStyle configurations:
- `checkstyle.xml` is a strict translation of `.editorconfig` in the code base (https://github.com/pac4j/pac4j/blob/master/.editorconfig). I suppose it's the style that are supposed to be followed. Unfortunately, as shown in #955 , the current code base has a large number of violations against these style specifications.
- `checkstyle-zero-vio.xml` is the actual style inferred from the existing code base, and thus is coherent with the code. If you run Checkstyle against this specification, there is 0 violations. 

The command to run Checkstyle is:
```
$ mvn checkstyle:check
```

As I use `checkstyle-zero-vio.xml` in `pom.xml`, the PR would __not__ affect the build process. However, changing it to `checkstyle.xml` would results in many violations (fixing them needs to revise the code).

### CODE REVIEW

**Comment by victornoel** [comment]
I think we should directly use the correct checkstyle configuration and fix the problems in one go :)

But are the violations related to indentation and stuffs like that or also to other stylistic issues (because the zero-vio file seems to contain much more than just things about indentation style…)

**Comment by tianyin** [comment]
@victornoel then we can apply `checkstyle.xml`
The violations include indentation, line length, and trailing white space (basically those 5 rules specified in `.editorconfig`; all of these rules are violated)

The zero-violation file is generated via a tool that infers the style of an existing code base
(it's strictly consistent with the current code base)
There're more rules than what is specified in `.editorconfig` (which are somehow followed by the current code)

**Comment by victornoel** [comment]
ok, so seems good to me then, could you apply the changes to the code and we will see how it looks like? :)

**Comment by leleuj** [comment]
Yes, I'm in line, we should follow our own `.editorconfig` and fix all violations.

**Comment by tianyin** [comment]
done.  you can run 
```
$ mvn checkstyle:check
```
to examine and fix the violations.

**Comment by victornoel** [comment]
@tianyin but could you actually apply the changes and put the in a commit? As well as enabling checkstyle in the travis build?

**Comment by leleuj** [comment]
@tianyin Can we complete this and integrate the checkstyle verification in the build? As well as the appropriate changes? Thx

**Comment by leleuj** [comment]
Thanks

**Pull request merged**
