### PR TITLE
Fix issue with saml ssocircle when using internet explorer

### PR DESCRIPTION
**Pull request by garpinc**
Chrome works but when using POST authentication binding from internet explorer I'm getting following stack trace. SSOcircle is doing something different with IE.

```
Caused by: org.opensaml.messaging.decoder.MessageDecodingException: Error unmarshalling message from input stream
	at org.pac4j.saml.transport.AbstractPac4jDecoder.unmarshallMessage(AbstractPac4jDecoder.java:127)
	at org.pac4j.saml.transport.Pac4jHTTPPostDecoder.doDecode(Pac4jHTTPPostDecoder.java:39)
	at org.opensaml.messaging.decoder.AbstractMessageDecoder.decode(AbstractMessageDecoder.java:58)
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageReceiver.getDecoder(SAML2WebSSOMessageReceiver.java:28)
	... 63 common frames omitted
Caused by: net.shibboleth.utilities.java.support.xml.XMLParserException: Unable to read data from input stream
	at net.shibboleth.utilities.java.support.xml.BasicParserPool.parse(BasicParserPool.java:255)
	at org.opensaml.core.xml.util.XMLObjectSupport.unmarshallFromInputStream(XMLObjectSupport.java:235)
	at org.pac4j.saml.transport.AbstractPac4jDecoder.unmarshallMessage(AbstractPac4jDecoder.java:124)
	... 66 common frames omitted
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 2 of 3-byte UTF-8 sequence.
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:408)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.arrangeCapacity(XMLEntityScanner.java:1761)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipString(XMLEntityScanner.java:1799)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:156)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at net.shibboleth.utilities.java.support.xml.BasicParserPool$DocumentBuilderProxy.parse(BasicParserPool.java:785)
	at net.shibboleth.utilities.java.support.xml.BasicParserPool.parse(BasicParserPool.java:247)
```

### CODE REVIEW

**Comment by leleuj** [comment]
I'm trying to understand what the issue is. Reading your code, it seems that the body content is not a raw SAML response, but a list of key=value (like a query string) with the SAML response as one of the key=value.
I understand your change but I think it breaks the behavior when a raw SAML response is directly passed in the body as you always try to parse the body content.

Can you add a test to confirm this still works and fix the code if need be? Thanks

**Comment by garpinc** [comment]
Do u have an example of a raw saml response since obviously ssocircle doesn't provide one



- Garry



-------- Original message --------

**Comment by garpinc** [comment]
I've added additional test case

**Comment by mmoayyed** [comment]
> SSOcircle is doing something different with IE.

I am not sure I understand this. Why is this happening with IE and not with Chrome?

**Comment by garpinc** [comment]
> > SSOcircle is doing something different with IE.
> 
> I am not sure I understand this. Why is this happening with IE and not with Chrome?

I have no idea.. But that’s what I found through testing. I’m assuming it’s detecting browser to decide what to send back

**Comment by mmoayyed** [comment]
Could you indicate what version of IE is this?

**Comment by garpinc** [comment]
> Could you indicate what version of IE is this?

I tested with version 11.476.18362.0

**Comment by leleuj** [comment]
I'm surprised this additionnal test works, but it's good. Merging...

**Comment by leleuj** [comment]
BTW, I slightly refactored your code: https://github.com/pac4j/pac4j/commit/6dd694bf67da3d4458400485c79a76382f8011ec

**Pull request merged**
