### PR TITLE
Upgrade nimbus-jwt to 9.24.1

### PR DESCRIPTION
**Pull request by mmoayyed**
The `com.nimbusds.jose.shaded` components are no longer available in the latest upgrade. Instead, they are changed to use Map and List.

### CODE REVIEW

**Comment by mmoayyed** [comment]
I think this is the commit that affects pac4j: https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/74a64ad633771362d7a30edb359f9e02e6774143

**Comment by mmoayyed** [comment]
Hi @leleuj have you had a chance to take a look at this?

**Comment by leleuj** [comment]
@apereocas-bot runci

**Comment by leleuj** [comment]
LGTM let's see if the build pass

**Comment by leleuj** [comment]
Just a small failure: `PMD Failure: org.pac4j.oidc.profile.OidcProfileTests:11 Rule:UnusedImports Priority:4 Avoid unused imports such as 'org.pac4j.core.profile.UserProfile'.`

**Comment by mmoayyed** [comment]
Thanks. Cleaned up the import

**Comment by leleuj** [comment]
BTW, I plan to cut the 5.4.6 release tomorrow.

**Pull request merged**
